---
- name: Playbook for adding users from file
  hosts: wordpress
  gather_facts: no
  tasks:
  - name: Loading user list
    read_csv:
      path: ../files/users.txt
    register: users
    delegate_to: localhost
    become: false

  - name: Adding users to the system
    user:
      name: "{{ item.username }}"
      state: present
      password: "{{ item.hashed_password }}"
    loop: "{{ users.list }}"
