---
- name: Installing LAMP
  hosts: wordpress
  gather_facts: no
  vars:
    packages: []
  tasks:
  - name: Loading list of LAMP packages
    set_fact:
      packages: "{{ packages + [item] }}"
    with_lines: cat ../files/task_3.txt

  - name: Changing PHP stream
    command: "{{ item }}"
    loop:
      - yum module reset php -y
      - yum module enable php:7.4 -y

  - name: Installing LAMP packages
    yum:
      name: "{{ packages }}"
      state: latest
