---
- name: Configuring banner and MOTD
  hosts: wordpress
  tasks:
    - name: Configuring banner
      template:
        src: ../files/task_4_banner.txt
        dest: /etc/banner

    - name: Configuring MOTD
      copy:
        src: ../files/task_4_motd.txt
        dest: /etc/motd
